### ISSUE TITLE
How to support data type numeric(20,10)

### ISSUE THREAD

**Issue by li-xiangdong** [bytefish/PgBulkInsert#10]
How to support data type numeric(20,10)

**Comment by bytefish** [comment]
I will look into it. But I don't think I can quickly come up with something. A custom NumericHandler will be needed for sure, but I have no idea how to do it for now.

**Comment by bytefish** [comment]
This is how Npgsql handles Numeric Types: [NumericHandler.cs](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/TypeHandlers/NumericHandlers/NumericHandler.cs).

**Comment by bytefish** [comment]
The Intermine library has a great implementation for supporting Numeric Datatypes with Postgresql Binary Copy Format:

* [BatchWriterPostgresCopyImpl.java](https://github.com/intermine/intermine/blob/master/intermine/objectstore/main/src/org/intermine/sql/writebatch/BatchWriterPostgresCopyImpl.java)

I have just tested the Numeric Writer of Intermine and it works perfectly. But I cannot use the Intermine implementation even with the correct attribution, because my library is under MIT License and Intermine has been released under terms of the GPL license. I don't want to release this library under GPL, so it may take some time to rewrite the Numeric part.

**Comment by bytefish** [comment]
I have added support for Numeric Data Types, please use the ``mapNumeric`` Array for supporting NumericDataTypes. Please note, that ``mapNumeric`` only accepts a ``BigDecimal`` as Java Type. If you need to map an ``Integer`` Property to a ``Numeric`` field, you could write your own Value Handler. 

Please let me know, if you need help doing it.

This functionality will be added with the next release.

**Comment by bytefish** [comment]
I have added a sample, that shows how to write a Double into a Numeric column:

* https://github.com/bytefish/PgBulkInsert/blob/master/PgBulkInsert/src/test/java/de/bytefish/pgbulkinsert/integration/CustomValueHandlerIntegrationTest.java

This technique will work with other types, too.

**Comment by bytefish** [comment]
I have released Version 1.3, which will be available in the Central Maven Repositories in some hours.
