### ISSUE TITLE
table name or field name case sensitive or key string like 'binary' as field name

### ISSUE THREAD

**Issue by tangyibo** [bytefish/PgBulkInsert#48]
I test throw exception by postgresql driver when table name or field name case sensitive or key string like 'binary' as field name, so I think table name and field name should be quoted by charactor '"" in class de.bytefish.pgbulkinsert.row.SimpleRowWriter, like this:

`
package de.bytefish.pgbulkinsert.row;

import de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter;
import de.bytefish.pgbulkinsert.pgsql.handlers.ValueHandlerProvider;
import de.bytefish.pgbulkinsert.util.StringUtils;
import org.postgresql.PGConnection;
import org.postgresql.copy.PGCopyOutputStream;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.stream.Collectors;

public class SimpleRowWriter {

    public static class Table {

        private final String schema;
        private final String table;
        private final String[] columns;

        public Table(String table, String... columns) {
            this(null, table, columns);
        }

        public Table(String schema, String table, String... columns) {
            this.schema = schema;
            this.table = table;
            this.columns = columns;
        }

        public String getSchema() {
            return schema;
        }

        public String getTable() {
            return table;
        }

        public String[] getColumns() {
            return columns;
        }

        public String GetFullyQualifiedTableName() {
            if (StringUtils.isNullOrWhiteSpace(schema)) {
                return table;
            }
            return String.format("\"%1$s\".\"%2$s\"", schema, table);
        }
    }

    private final Table table;
    private final PgBinaryWriter writer;
    private final ValueHandlerProvider provider;
    private final Map<String, Integer> lookup;

    public SimpleRowWriter(Table table) {
        this.writer = new PgBinaryWriter();
        this.table = table;
        this.provider = new ValueHandlerProvider();

        this.lookup = new HashMap<>();

        for (int ordinal = 0; ordinal < table.columns.length; ordinal++) {
            lookup.put(table.columns[ordinal], ordinal);
        }
    }

    public void open(PGConnection connection) throws SQLException  {
        writer.open(new PGCopyOutputStream(connection, getCopyCommand(table), 1));
    }

    public synchronized void startRow(Consumer<SimpleRow> consumer) {

        writer.startRow(table.columns.length);

        SimpleRow row = new SimpleRow(provider, lookup);

        consumer.accept(row);

        row.writeRow(writer);
    }

    public void close() throws SQLException  {
        writer.close();
    }

    private static String getCopyCommand(Table table) {
        String commaSeparatedColumns = Arrays.stream(table.columns)
                .collect(Collectors.joining("\", \""));

        return String.format("COPY %1$s(\"%2$s\") FROM STDIN BINARY",
                table.GetFullyQualifiedTableName(),
                commaSeparatedColumns);
    }
}
`

**Comment by bytefish** [comment]
@tangyibo Thanks for your pull request and your interest in the library! For the quoting, I already did something similar in the PostgreSQLCopyHelper library here:

https://github.com/PostgreSQLCopyHelper/PostgreSQLCopyHelper/blob/51b433f9c27383a9ca661ab20c8d12648e805f88/src/PostgreSQLCopyHelper/Utils/NpgsqlUtils.cs#L36

Not everyone wants quoting probably. Maybe some users of the library are already quoting the columns and tables by themselves? We need to account for this.

As for reserved keywords... I really don't want to maintain a list of reserved keywords. If an error comes up, because someone used ``user`` while creating the table... then he definitely knows he quoted it when creating the table.

So I would give users of the library the choice. Maybe a method like the one in PostgreSQLCopyHelper is useful?

**Comment by bytefish** [comment]
I have added a constructor parameter ``usePostgresQuoting", which will quote all identifiers according to Postgres rules. I cannot automatically set this parameter to true, because I don't know if people started using the library without quoting... and I don't want their builds to break as it would be a breaking change.

As for Reserved Keywords: I will not add them, sorry.

**Comment by bytefish** [comment]
@tangyibo Thanks for raising the issue and bringing it to my attention. Also thanks for the effort you put into the Pull Request! 👍

**Comment by tangyibo** [comment]
多谢，我会持续关注此项目的动态。
