### ISSUE TITLE
Support automatic mapping through JPA models

### ISSUE THREAD

**Issue by cheffe** [bytefish/PgBulkInsert#54]
We have just found this great library and started to use it for our project. As of now we are using Spring Boot with Hibernate. Hence we have all models already written as JPA Pojos.

Right now I need to duplicate my mappings via implementing an`AbstractMapping` instance per entity. It would be great if a `JpaMapping` class would exist that we could use instead.

Maybe something like this is already in the making on your side?

**Comment by bytefish** [comment]
@cheffe That sounds like a great feature! Let me prototype something, which we can iterate on and see if it matches what you need! 👍

**Comment by bytefish** [comment]
It will take some moments, because while making a prototype I will also do something, that's long overdue: Turning the project into a Multi Module project. This way we can write additional modules like for the JPA mappings or Postgis, without everyone needing all possible Spring Boot JPA dependecies.

**Comment by cheffe** [comment]
Great thank you for the fast response, let me know if I can help somehow.

**Comment by bytefish** [comment]
@cheffe I have added an initial version, that we could take a look at! 

Here is how it would be used:

https://github.com/bytefish/PgBulkInsert/blob/f8d4601d313fbc029dbb54a5a699f18757fff242/PgBulkInsert/pgbulkinsert-jpa/src/test/java/de/bytefish/pgbulkinsert/jpa/JpaMappingTests.java#L75

In the initial implementation it is only able to map fields annotated with ``@Column``, because it is way too hard for me to analyze ``OneToMany`` and ``OneToOne`` relationships, After all the library is not really an ORM and I don't want it to be.

The field mapping is currently done in this beast here: 

https://github.com/bytefish/PgBulkInsert/blob/f8d4601d313fbc029dbb54a5a699f18757fff242/PgBulkInsert/pgbulkinsert-jpa/src/main/java/de/bytefish/pgbulkinsert/jpa/JpaMapping.java#L52

This is a bit ugly and not really configurable from the outside. And with my very limited Java Reflection-skills... I don't know if there is a way to make this look a little better. 

Please take a look at let me know what you think.

**Comment by bytefish** [comment]
@cheffe There is one thing, I am not sure of. So I turned the project into modules, so that modules could be written without modifying a stable core library. I want people to not change too much in their code if they are upgrading the library... except maybe changing the Maven dependencies. So I left the package name for the core module as is, and changed the groupId to ``de.bytefish.pgbulkinsert``. Does this structure and groupId make sense?

**Comment by cheffe** [comment]
That looks very good. I will try it out tomorrow. Thank you for the effort!

**Comment by cheffe** [comment]
About the structure that looks fine with what I got to know by now. There are loads of libraries that structure similar to this.

**Comment by cheffe** [comment]
Ok, I am working on it for a while now. We have the challenge that we are using Kotlin, not vanilla Java. Right now I have to deal with Kotlin enums vs Java. I think I may need to push a patch for that.

**Comment by bytefish** [comment]
Good! I have never used Kotlin, so I am not much of a help. Also I am creating all this as a new Major Release. So if we could improve the API, I am all in. Maybe you could push to the ``pgbulkinsert-jpa`` branch for now, so it could later be released altogether?

**Comment by cheffe** [comment]
It works except for enums, I have to take that with me over the weekend.

**Comment by bytefish** [comment]
Which Enums? Can you give me an example?

**Comment by bytefish** [comment]
OK. I have added support for ``@Enumerated`` for persisting as String / SmallInt. What do you think should an Enum Ordinal be persisted with? I think a SmallInt will suffice.

**Comment by bytefish** [comment]
@cheffe I have made some additions. It's now possible to pass a Column-to-DataType Mapping into the ``JpaMapping``. The reasoning is, that you probably don't want the defaults to be applied for the mapping. At the same time, I have also released a version ``5.0.0-alpha1`` to Maven. 

It would be great, if you could give me some feedback! 👍 

```xml
<dependency>
	<groupId>de.bytefish.pgbulkinsert</groupId>
	<artifactId>pgbulkinsert-core</artifactId>
	<version>5.0.0-alpha1</version>
</dependency>

<dependency>
	<groupId>de.bytefish.pgbulkinsert</groupId>
	<artifactId>pgbulkinsert-jpa</artifactId>
	<version>5.0.0-alpha1</version>
</dependency>
```

**Comment by cheffe** [comment]
Thanks a lot for your efforts. I will look into it after the breakfast :)

**Comment by cheffe** [comment]
I gave it a few shots yesterday. We are using entities that have implemented Spring's `Persistable` interface, plus they offer a combined ID class, like this

`@Entity
@IdClass(value = KpiEntityKey::class)
@Table(name = "kpi")
data class KpiEntity(
  @Column(name = "id") @Id val id: String,
  @Column(name = "snapshot") @Id val snapshot: String,
  @Column(name = "location") val location: String,
  @Column(name = "product") val product: String,
  @Column(name = "division") @Enumerated(EnumType.STRING) val division: Division,
  @Column(name = "type") @Id @Enumerated(EnumType.STRING) val type: KpiType,
  @Column(name = "time") @Id val time: LocalDate,
  @Column(name = "time_aggregation") @Enumerated(EnumType.STRING) @Id val timeAggregation: TimeUnit,
  @Column(name = "value") val value: Double,
  @Column(name = "unit") val unit: String,
  @Column(name = "source") @Id @Enumerated(EnumType.STRING) val source: Source
) : Persistable<KpiEntityKey> {

  override fun isNew(): Boolean {
    return true
  }

  override fun getId(): KpiEntityKey? {
    return KpiEntityKey(
      id,
      snapshot,
      type,
      time,
      timeAggregation,
      source
    )
  }
}`

**Comment by cheffe** [comment]
Problem with this is that the method `getId()` introduces a read only property, hence we would need to call the alternate constructor `PropertyDescriptor(String propertyName, Class<?> beanClass, String readMethodName, String writeMethodName)` of the PropertyDescriptor, with `writeMethodName` being null.

I forked yesterday and am trying to propose a change.

**Comment by cheffe** [comment]
I have reproduced and solved the issue within the `JpaMappingTest`, please checkout my pull request.

**Comment by bytefish** [comment]
I would like to release it. What do you think?

**Comment by cheffe** [comment]
Looks good to me. I would include it in our next release. That we you would get some productive runs. These routines run on a daily basis.

**Comment by bytefish** [comment]
OK! I write some documentation and prepare a release. 👍

**Comment by bytefish** [comment]
OK! The ``5.0.0`` is released to the Central Maven Repository. It should be available within some hours. I have also merged all changes to the master branch. Thanks for your efforts and you patience. :-) 

I am closing this issue, but if a problems comes up feel free to reopen or file a separate issue.
