### ISSUE TITLE
Mapping error for Timestamp

### ISSUE THREAD

**Issue by idoor88** [bytefish/PgBulkInsert#60]
I need to map the table email to a domain model EmailPg, where I have:
public Timestamp getEmailCreateTime() {
		return emailCreateTime;
	}
and the table field email_create_time is data type of timestamp without time zone,
but when I map the table field as the following:
mapTimeStamp("email_create_time", EmailPg::getEmailCreateTime);

I got this error:

incompatible types: bad return type in method reference
[ERROR] java.sql.Timestamp cannot be converted to java.time.LocalDateTime

I am using:
<dependency>
			<groupId>de.bytefish.pgbulkinsert</groupId>
			<artifactId>pgbulkinsert-core</artifactId>
			<version>5.1.0-alpha1</version>
		</dependency>

also tried version 5.0.0, I got the same error.
any clue?
Thanks

**Comment by bytefish** [comment]
For now I would suggest to convert it :

```java
mapTimeStamp("email_create_time", x -> x != null ? x.getEmailCreateTime().toLocalDateTime() : null);
```

I know it's not the perfect API, more on this later.

Here is a full example:

```java
public class EMail {

    private Timestamp emailCreateTime;

    public Timestamp getEmailCreateTime() {
        return emailCreateTime;
    }

    public void setEmailCreateTime(Timestamp emailCreateTime) {
        this.emailCreateTime = emailCreateTime;
    }
}

public class EMailMapping extends AbstractMapping<EMail>
{
    public EMailMapping(String schema) {
        super(schema, "unit_test");

        mapTimeStamp("email_create_time", x -> x != null ? x.getEmailCreateTime().toLocalDateTime() : null);
    }
}
```

The problem is... I am hitting the limits with my API design. :( 

I am using ``Function<S,T>`` interfaces, which cannot be overloaded. So I am either stuck with ``mapTimeStamp`` and ``mapTimeStamp2``... or I need to introduce some kind of additional reflection magic in the handler.

This is not optimal, I know. I think about the API.

In the meantime the above works fine.
